selected_scheme scheme-basic
TEXDIR /usr/local/texlive
TEXMFSYSCONFIG /usr/local/texlive/texmf-config
TEXMFSYSVAR /usr/local/texlive/texmf-var
TEXMFHOME ~/texlive/texmf
TEXMFVAR ~/texlive/texmf-var
TEXMFCONFIG  ~/texlive/texmf-config
TEXMFLOCAL ~/texlive/texmf-local
option_doc 0
option_src 0
